insert into stocks (title, price, stock, status, category_id) values ('Sauce - Rosee', 386, 26, 'dispatched', 4);
insert into stocks (title, price, stock, status, category_id) values ('Wine - Touraine Azay - Le - Rideau', 523, 93, 'ordered', 3);
insert into stocks (title, price, stock, status, category_id) values ('Contreau', 623, 58, 'ordered', 11);
insert into stocks (title, price, stock, status, category_id) values ('Wine - Two Oceans Cabernet', 191, 19, 'ordered', 8);
insert into stocks (title, price, stock, status, category_id) values ('Versatainer Nc - 888', 484, 53, 'dispatched', 10);
insert into stocks (title, price, stock, status, category_id) values ('Pan Grease', 586, 44, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('Parasol Pick Stir Stick', 719, 31, 'dispatched', 11);
insert into stocks (title, price, stock, status, category_id) values ('Lamb - Bones', 501, 18, 'dispatched', 8);
insert into stocks (title, price, stock, status, category_id) values ('Wheat - Soft Kernal Of Wheat', 661, 42, 'dispatched', 8);
insert into stocks (title, price, stock, status, category_id) values ('Eel Fresh', 909, 16, 'ordered', 11);
insert into stocks (title, price, stock, status, category_id) values ('Pasta - Orecchiette', 659, 3, 'ordered', 11);
insert into stocks (title, price, stock, status, category_id) values ('Shopper Bag - S - 4', 657, 90, 'ordered', 10);
insert into stocks (title, price, stock, status, category_id) values ('Cheese - Mascarpone', 481, 92, 'dispatched', 2);
insert into stocks (title, price, stock, status, category_id) values ('Tray - Foam, Square 4 - S', 625, 42, 'ordered', 7);
insert into stocks (title, price, stock, status, category_id) values ('Cheese - Swiss Sliced', 441, 65, 'dispatched', 5);
insert into stocks (title, price, stock, status, category_id) values ('Spring Roll Wrappers', 732, 98, 'ordered', 4);
insert into stocks (title, price, stock, status, category_id) values ('Devonshire Cream', 795, 84, 'ordered', 8);
insert into stocks (title, price, stock, status, category_id) values ('Bread - Malt', 374, 45, 'dispatched', 8);
insert into stocks (title, price, stock, status, category_id) values ('Chervil - Fresh', 874, 71, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Pasta - Lasagna Noodle, Frozen', 933, 37, 'ordered', 4);
insert into stocks (title, price, stock, status, category_id) values ('Nestea - Ice Tea, Diet', 239, 39, 'ordered', 3);
insert into stocks (title, price, stock, status, category_id) values ('Haggis', 657, 94, 'dispatched', 5);
insert into stocks (title, price, stock, status, category_id) values ('Beef - Top Butt Aaa', 284, 30, 'dispatched', 10);
insert into stocks (title, price, stock, status, category_id) values ('Dried Apple', 646, 31, 'ordered', 8);
insert into stocks (title, price, stock, status, category_id) values ('Tomatoes - Hot House', 750, 75, 'ordered', 11);
insert into stocks (title, price, stock, status, category_id) values ('Pike - Frozen Fillet', 770, 35, 'ordered', 4);
insert into stocks (title, price, stock, status, category_id) values ('Beans - Kidney, Canned', 267, 23, 'dispatched', 7);
insert into stocks (title, price, stock, status, category_id) values ('Raspberries - Fresh', 668, 52, 'ordered', 11);
insert into stocks (title, price, stock, status, category_id) values ('Cake - Dulce De Leche', 207, 54, 'ordered', 1);
insert into stocks (title, price, stock, status, category_id) values ('Bagel - Plain', 619, 77, 'dispatched', 8);
insert into stocks (title, price, stock, status, category_id) values ('Potatoes - Mini White 3 Oz', 817, 82, 'dispatched', 10);
insert into stocks (title, price, stock, status, category_id) values ('Brocolinni - Gaylan, Chinese', 535, 63, 'dispatched', 2);
insert into stocks (title, price, stock, status, category_id) values ('Cake - Miini Cheesecake Cherry', 232, 49, 'dispatched', 2);
insert into stocks (title, price, stock, status, category_id) values ('Bag - Bread, White, Plain', 735, 90, 'ordered', 6);
insert into stocks (title, price, stock, status, category_id) values ('Beer - Sleemans Honey Brown', 497, 68, 'dispatched', 8);
insert into stocks (title, price, stock, status, category_id) values ('Flower - Carnations', 206, 92, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Schnappes Peppermint - Walker', 316, 58, 'ordered', 6);
insert into stocks (title, price, stock, status, category_id) values ('Milkettes - 2%', 770, 70, 'ordered', 6);
insert into stocks (title, price, stock, status, category_id) values ('Horseradish Root', 700, 99, 'ordered', 1);
insert into stocks (title, price, stock, status, category_id) values ('Soup - French Onion', 532, 19, 'dispatched', 8);
insert into stocks (title, price, stock, status, category_id) values ('Beer - Sleemans Honey Brown', 764, 96, 'ordered', 2);
insert into stocks (title, price, stock, status, category_id) values ('Fish - Soup Base, Bouillon', 836, 90, 'ordered', 7);
insert into stocks (title, price, stock, status, category_id) values ('Relish', 869, 93, 'dispatched', 9);
insert into stocks (title, price, stock, status, category_id) values ('Squash - Pattypan, Yellow', 169, 19, 'ordered', 10);
insert into stocks (title, price, stock, status, category_id) values ('Jam - Raspberry,jar', 957, 28, 'ordered', 7);
insert into stocks (title, price, stock, status, category_id) values ('Lamb - Loin, Trimmed, Boneless', 251, 81, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Truffle Shells - Semi - Sweet', 460, 47, 'ordered', 2);
insert into stocks (title, price, stock, status, category_id) values ('Soup - Canadian Pea, Dry Mix', 579, 29, 'ordered', 4);
insert into stocks (title, price, stock, status, category_id) values ('Versatainer Nc - 9388', 462, 37, 'ordered', 10);
insert into stocks (title, price, stock, status, category_id) values ('Puff Pastry - Sheets', 243, 92, 'ordered', 6);
insert into stocks (title, price, stock, status, category_id) values ('Lobster - Baby, Boiled', 558, 34, 'ordered', 11);
insert into stocks (title, price, stock, status, category_id) values ('Bread - French Stick', 639, 65, 'dispatched', 5);
insert into stocks (title, price, stock, status, category_id) values ('Monkfish Fresh - Skin Off', 393, 51, 'ordered', 4);
insert into stocks (title, price, stock, status, category_id) values ('Shrimp, Dried, Small / Lb', 168, 73, 'ordered', 6);
insert into stocks (title, price, stock, status, category_id) values ('Shopper Bag - S - 4', 950, 59, 'ordered', 7);
insert into stocks (title, price, stock, status, category_id) values ('Lid Coffeecup 12oz D9542b', 200, 88, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Bols Melon Liqueur', 539, 92, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Rum - Mount Gay Eclipes', 216, 96, 'dispatched', 10);
insert into stocks (title, price, stock, status, category_id) values ('Lemonade - Island Tea, 591 Ml', 804, 4, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Ham - Cooked Bayonne Tinned', 279, 47, 'dispatched', 8);
insert into stocks (title, price, stock, status, category_id) values ('Parsnip', 778, 97, 'dispatched', 6);
insert into stocks (title, price, stock, status, category_id) values ('Bread - Pain Au Liat X12', 671, 45, 'ordered', 6);
insert into stocks (title, price, stock, status, category_id) values ('Squid Ink', 981, 94, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Truffle Paste', 150, 73, 'ordered', 10);
insert into stocks (title, price, stock, status, category_id) values ('Irish Cream - Baileys', 877, 28, 'ordered', 8);
insert into stocks (title, price, stock, status, category_id) values ('Fond - Chocolate', 338, 99, 'dispatched', 7);
insert into stocks (title, price, stock, status, category_id) values ('Lid - 3oz Med Rec', 516, 89, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('Chocolate Bar - Coffee Crisp', 190, 63, 'dispatched', 10);
insert into stocks (title, price, stock, status, category_id) values ('Lamb - Shoulder', 521, 87, 'ordered', 3);
insert into stocks (title, price, stock, status, category_id) values ('Coke - Diet, 355 Ml', 303, 34, 'ordered', 2);
insert into stocks (title, price, stock, status, category_id) values ('Pate - Liver', 171, 72, 'ordered', 3);
insert into stocks (title, price, stock, status, category_id) values ('Beer - Tetleys', 396, 93, 'dispatched', 6);
insert into stocks (title, price, stock, status, category_id) values ('Beans - Navy, Dry', 342, 30, 'dispatched', 6);
insert into stocks (title, price, stock, status, category_id) values ('Eggplant - Regular', 211, 98, 'ordered', 11);
insert into stocks (title, price, stock, status, category_id) values ('Bread - French Stick', 286, 75, 'ordered', 4);
insert into stocks (title, price, stock, status, category_id) values ('Halibut - Fletches', 307, 98, 'ordered', 2);
insert into stocks (title, price, stock, status, category_id) values ('Food Colouring - Pink', 475, 62, 'ordered', 6);
insert into stocks (title, price, stock, status, category_id) values ('Pineapple - Regular', 846, 52, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('Lemonade - Strawberry, 591 Ml', 550, 27, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('Extract - Raspberry', 414, 88, 'ordered', 1);
insert into stocks (title, price, stock, status, category_id) values ('Chinese Foods - Cantonese', 608, 56, 'dispatched', 2);
insert into stocks (title, price, stock, status, category_id) values ('Ecolab Digiclean Mild Fm', 488, 17, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('Dragon Fruit', 598, 36, 'ordered', 2);
insert into stocks (title, price, stock, status, category_id) values ('Mace', 682, 69, 'ordered', 8);
insert into stocks (title, price, stock, status, category_id) values ('Olive - Spread Tapenade', 798, 34, 'ordered', 4);
insert into stocks (title, price, stock, status, category_id) values ('Pastry - Chocolate Marble Tea', 736, 98, 'dispatched', 6);
insert into stocks (title, price, stock, status, category_id) values ('Pop - Club Soda Can', 626, 12, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Veal - Nuckle', 334, 28, 'ordered', 10);
insert into stocks (title, price, stock, status, category_id) values ('Wine - Red Oakridge Merlot', 476, 86, 'dispatched', 2);
insert into stocks (title, price, stock, status, category_id) values ('Yoplait - Strawbrasp Peac', 299, 86, 'dispatched', 2);
insert into stocks (title, price, stock, status, category_id) values ('Soup - Campbells Mushroom', 378, 69, 'ordered', 1);
insert into stocks (title, price, stock, status, category_id) values ('Basil - Seedlings Cookstown', 614, 38, 'ordered', 6);
insert into stocks (title, price, stock, status, category_id) values ('Fruit Mix - Light', 252, 72, 'dispatched', 5);
insert into stocks (title, price, stock, status, category_id) values ('Sauce - Mint', 368, 57, 'dispatched', 9);
insert into stocks (title, price, stock, status, category_id) values ('Chicken - Whole Fryers', 755, 90, 'dispatched', 8);
insert into stocks (title, price, stock, status, category_id) values ('Cleaner - Bleach', 786, 15, 'ordered', 2);
insert into stocks (title, price, stock, status, category_id) values ('Anchovy In Oil', 289, 19, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Beer - Camerons Cream Ale', 156, 17, 'ordered', 3);
insert into stocks (title, price, stock, status, category_id) values ('Wine - Manischewitz Concord', 742, 28, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('Sugar - Cubes', 864, 10, 'ordered', 9);
insert into stocks (title, price, stock, status, category_id) values ('Longos - Grilled Veg Sandwiches', 324, 58, 'ordered', 2);
insert into stocks (title, price, stock, status, category_id) values ('Tomatoes Tear Drop', 607, 27, 'dispatched', 10);
insert into stocks (title, price, stock, status, category_id) values ('Mushroom Morel Fresh', 119, 79, 'ordered', 8);
insert into stocks (title, price, stock, status, category_id) values ('Cup - 6oz, Foam', 398, 42, 'ordered', 8);
insert into stocks (title, price, stock, status, category_id) values ('Ice Cream - Turtles Stick Bar', 658, 69, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Cheese - Brick With Onion', 579, 44, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Lamb - Whole, Fresh', 582, 55, 'ordered', 11);
insert into stocks (title, price, stock, status, category_id) values ('Chicken Giblets', 486, 94, 'ordered', 6);
insert into stocks (title, price, stock, status, category_id) values ('Oil - Shortening,liqud, Fry', 105, 35, 'ordered', 9);
insert into stocks (title, price, stock, status, category_id) values ('Chocolate - Semi Sweet', 426, 11, 'dispatched', 11);
insert into stocks (title, price, stock, status, category_id) values ('Wine - Kwv Chenin Blanc South', 911, 32, 'ordered', 2);
insert into stocks (title, price, stock, status, category_id) values ('Sauce - Apple, Unsweetened', 358, 49, 'ordered', 4);
insert into stocks (title, price, stock, status, category_id) values ('Vinegar - Red Wine', 752, 37, 'dispatched', 2);
insert into stocks (title, price, stock, status, category_id) values ('Tomatoes Tear Drop Yellow', 242, 10, 'dispatched', 6);
insert into stocks (title, price, stock, status, category_id) values ('Kippers - Smoked', 909, 12, 'ordered', 1);
insert into stocks (title, price, stock, status, category_id) values ('Shallots', 478, 68, 'dispatched', 9);
insert into stocks (title, price, stock, status, category_id) values ('Vinegar - Balsamic, White', 151, 46, 'dispatched', 9);
insert into stocks (title, price, stock, status, category_id) values ('Lettuce - Romaine, Heart', 162, 10, 'ordered', 6);
insert into stocks (title, price, stock, status, category_id) values ('Garam Marsala', 119, 70, 'dispatched', 10);
insert into stocks (title, price, stock, status, category_id) values ('Bread - Pumpernickel', 652, 87, 'dispatched', 11);
insert into stocks (title, price, stock, status, category_id) values ('Doilies - 7, Paper', 746, 18, 'dispatched', 10);
insert into stocks (title, price, stock, status, category_id) values ('Appetizer - Mushroom Tart', 618, 26, 'ordered', 10);
insert into stocks (title, price, stock, status, category_id) values ('Rolled Oats', 640, 12, 'ordered', 10);
insert into stocks (title, price, stock, status, category_id) values ('Juice - Apple 284ml', 671, 11, 'dispatched', 6);
insert into stocks (title, price, stock, status, category_id) values ('Split Peas - Green, Dry', 782, 31, 'dispatched', 5);
insert into stocks (title, price, stock, status, category_id) values ('Juice - Pineapple, 48 Oz', 206, 50, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('Isomalt', 300, 64, 'dispatched', 10);
insert into stocks (title, price, stock, status, category_id) values ('Rum - Light, Captain Morgan', 572, 78, 'dispatched', 7);
insert into stocks (title, price, stock, status, category_id) values ('Bacardi Mojito', 573, 26, 'dispatched', 5);
insert into stocks (title, price, stock, status, category_id) values ('Chinese Foods - Chicken', 567, 91, 'ordered', 2);
insert into stocks (title, price, stock, status, category_id) values ('Venison - Striploin', 151, 81, 'ordered', 1);
insert into stocks (title, price, stock, status, category_id) values ('Dikon', 514, 44, 'dispatched', 7);
insert into stocks (title, price, stock, status, category_id) values ('Ham - Virginia', 687, 59, 'ordered', 9);
insert into stocks (title, price, stock, status, category_id) values ('Soup Campbells', 911, 55, 'ordered', 9);
insert into stocks (title, price, stock, status, category_id) values ('Lobak', 863, 5, 'ordered', 2);
insert into stocks (title, price, stock, status, category_id) values ('Cake Sheet Combo Party Pack', 498, 58, 'ordered', 4);
insert into stocks (title, price, stock, status, category_id) values ('Wine - Periguita Fonseca', 958, 42, 'dispatched', 4);
insert into stocks (title, price, stock, status, category_id) values ('Grapes - Red', 131, 58, 'ordered', 6);
insert into stocks (title, price, stock, status, category_id) values ('Longos - Lasagna Veg', 855, 5, 'dispatched', 9);
insert into stocks (title, price, stock, status, category_id) values ('Wine - Chardonnay Mondavi', 507, 10, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Beef - Short Loin', 733, 60, 'ordered', 2);
insert into stocks (title, price, stock, status, category_id) values ('Turnip - Wax', 700, 52, 'dispatched', 11);
insert into stocks (title, price, stock, status, category_id) values ('Lettuce Romaine Chopped', 137, 98, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('Cabbage Roll', 446, 37, 'dispatched', 6);
insert into stocks (title, price, stock, status, category_id) values ('Quail - Jumbo Boneless', 854, 47, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Triple Sec - Mcguinness', 984, 30, 'ordered', 6);
insert into stocks (title, price, stock, status, category_id) values ('Water - Tonic', 258, 66, 'ordered', 3);
insert into stocks (title, price, stock, status, category_id) values ('Rice Paper', 513, 83, 'ordered', 11);
insert into stocks (title, price, stock, status, category_id) values ('Pork - Shoulder', 850, 83, 'ordered', 6);
insert into stocks (title, price, stock, status, category_id) values ('Beef - Tongue, Cooked', 673, 72, 'ordered', 4);
insert into stocks (title, price, stock, status, category_id) values ('Syrup - Monin, Swiss Choclate', 914, 13, 'dispatched', 6);
insert into stocks (title, price, stock, status, category_id) values ('Dates', 272, 97, 'ordered', 9);
insert into stocks (title, price, stock, status, category_id) values ('Garbage Bag - Clear', 160, 93, 'ordered', 2);
insert into stocks (title, price, stock, status, category_id) values ('Bread Base - Italian', 990, 46, 'ordered', 11);
insert into stocks (title, price, stock, status, category_id) values ('Wine - Masi Valpolocell', 715, 13, 'dispatched', 7);
insert into stocks (title, price, stock, status, category_id) values ('Contreau', 669, 75, 'ordered', 10);
insert into stocks (title, price, stock, status, category_id) values ('Squeeze Bottle', 569, 72, 'dispatched', 5);
insert into stocks (title, price, stock, status, category_id) values ('Long Island Ice Tea', 145, 93, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Pork - Suckling Pig', 712, 100, 'dispatched', 4);
insert into stocks (title, price, stock, status, category_id) values ('Tomatoes - Cherry, Yellow', 508, 95, 'ordered', 2);
insert into stocks (title, price, stock, status, category_id) values ('Muffin Mix - Carrot', 997, 9, 'dispatched', 7);
insert into stocks (title, price, stock, status, category_id) values ('Wine - Red, Mouton Cadet', 771, 7, 'ordered', 3);
insert into stocks (title, price, stock, status, category_id) values ('Nut - Pistachio, Shelled', 777, 34, 'ordered', 1);
insert into stocks (title, price, stock, status, category_id) values ('Cheese - Le Cheve Noir', 225, 33, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('Crab - Meat Combo', 782, 38, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Creme De Banane - Marie', 881, 88, 'dispatched', 6);
insert into stocks (title, price, stock, status, category_id) values ('Ecolab - Hobart Upr Prewash Arm', 961, 72, 'dispatched', 4);
insert into stocks (title, price, stock, status, category_id) values ('Squid - U - 10 Thailand', 339, 8, 'ordered', 3);
insert into stocks (title, price, stock, status, category_id) values ('Oil - Avocado', 497, 19, 'ordered', 1);
insert into stocks (title, price, stock, status, category_id) values ('Muskox - French Rack', 828, 99, 'dispatched', 6);
insert into stocks (title, price, stock, status, category_id) values ('Cranberry Foccacia', 339, 81, 'ordered', 10);
insert into stocks (title, price, stock, status, category_id) values ('Kale - Red', 961, 58, 'ordered', 4);
insert into stocks (title, price, stock, status, category_id) values ('Latex Rubber Gloves Size 9', 571, 9, 'dispatched', 9);
insert into stocks (title, price, stock, status, category_id) values ('Rum - Dark, Bacardi, Black', 566, 9, 'dispatched', 2);
insert into stocks (title, price, stock, status, category_id) values ('Sobe - Green Tea', 497, 82, 'ordered', 11);
insert into stocks (title, price, stock, status, category_id) values ('Soup - Campbells, Minestrone', 612, 99, 'dispatched', 11);
insert into stocks (title, price, stock, status, category_id) values ('Shallots', 333, 24, 'ordered', 9);
insert into stocks (title, price, stock, status, category_id) values ('Temperature Recording Station', 368, 75, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('Pork - Butt, Boneless', 908, 91, 'ordered', 6);
insert into stocks (title, price, stock, status, category_id) values ('Soup Campbells Turkey Veg.', 124, 9, 'dispatched', 11);
insert into stocks (title, price, stock, status, category_id) values ('Radish', 904, 100, 'dispatched', 2);
insert into stocks (title, price, stock, status, category_id) values ('Juice - Grape, White', 627, 9, 'ordered', 9);
insert into stocks (title, price, stock, status, category_id) values ('Sping Loaded Cup Dispenser', 986, 29, 'ordered', 6);
insert into stocks (title, price, stock, status, category_id) values ('Pork - Backfat', 213, 8, 'ordered', 4);
insert into stocks (title, price, stock, status, category_id) values ('Oven Mitts - 15 Inch', 415, 15, 'dispatched', 8);
insert into stocks (title, price, stock, status, category_id) values ('Wine - Lou Black Shiraz', 671, 74, 'dispatched', 4);
insert into stocks (title, price, stock, status, category_id) values ('Rice - Sushi', 350, 12, 'ordered', 7);
insert into stocks (title, price, stock, status, category_id) values ('Crawfish', 714, 5, 'ordered', 1);
insert into stocks (title, price, stock, status, category_id) values ('Wine - Alicanca Vinho Verde', 702, 26, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Appetizer - Spring Roll, Veg', 301, 15, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('Wine - White, Schroder And Schyl', 297, 79, 'dispatched', 11);
insert into stocks (title, price, stock, status, category_id) values ('Iced Tea Concentrate', 929, 94, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Mushroom - Morel Frozen', 615, 17, 'ordered', 9);
insert into stocks (title, price, stock, status, category_id) values ('Ice Cream - Vanilla', 392, 88, 'dispatched', 8);
insert into stocks (title, price, stock, status, category_id) values ('Olives - Kalamata', 814, 42, 'ordered', 8);
insert into stocks (title, price, stock, status, category_id) values ('Wine - Semi Dry Riesling Vineland', 496, 49, 'ordered', 6);
insert into stocks (title, price, stock, status, category_id) values ('Appetizer - Chicken Satay', 915, 58, 'dispatched', 7);
insert into stocks (title, price, stock, status, category_id) values ('Cheese - Feta', 313, 95, 'ordered', 1);
insert into stocks (title, price, stock, status, category_id) values ('Cocoa Butter', 525, 7, 'dispatched', 11);
insert into stocks (title, price, stock, status, category_id) values ('Monkfish - Fresh', 873, 19, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Nut - Almond, Blanched, Ground', 595, 18, 'ordered', 9);
insert into stocks (title, price, stock, status, category_id) values ('Soup - Campbells Beef Stew', 396, 99, 'ordered', 1);
insert into stocks (title, price, stock, status, category_id) values ('Spinach - Packaged', 721, 83, 'dispatched', 4);
insert into stocks (title, price, stock, status, category_id) values ('Jameson Irish Whiskey', 872, 85, 'dispatched', 6);
insert into stocks (title, price, stock, status, category_id) values ('Wine - Magnotta - Cab Sauv', 500, 94, 'dispatched', 11);
insert into stocks (title, price, stock, status, category_id) values ('Flour - Buckwheat, Dark', 594, 69, 'dispatched', 10);
insert into stocks (title, price, stock, status, category_id) values ('Bread - Hot Dog Buns', 867, 43, 'ordered', 11);
insert into stocks (title, price, stock, status, category_id) values ('Rosemary - Fresh', 507, 40, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Green Tea Refresher', 676, 59, 'ordered', 7);
insert into stocks (title, price, stock, status, category_id) values ('Wine - Magnotta - Bel Paese White', 596, 63, 'dispatched', 5);
insert into stocks (title, price, stock, status, category_id) values ('Cheese - Colby', 663, 9, 'ordered', 3);
insert into stocks (title, price, stock, status, category_id) values ('Mangostein', 515, 33, 'ordered', 1);
insert into stocks (title, price, stock, status, category_id) values ('Canadian Emmenthal', 729, 37, 'ordered', 3);
insert into stocks (title, price, stock, status, category_id) values ('Wasabi Paste', 280, 76, 'ordered', 10);
insert into stocks (title, price, stock, status, category_id) values ('Scallops - 20/30', 261, 62, 'ordered', 8);
insert into stocks (title, price, stock, status, category_id) values ('Peach - Fresh', 929, 91, 'ordered', 2);
insert into stocks (title, price, stock, status, category_id) values ('Asparagus - White, Canned', 971, 69, 'ordered', 4);
insert into stocks (title, price, stock, status, category_id) values ('Rice - Basmati', 331, 93, 'ordered', 4);
insert into stocks (title, price, stock, status, category_id) values ('Cabbage - Red', 915, 88, 'dispatched', 2);
insert into stocks (title, price, stock, status, category_id) values ('Cheese Cloth No 60', 718, 14, 'ordered', 6);
insert into stocks (title, price, stock, status, category_id) values ('Beer - True North Strong Ale', 541, 68, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Glass Clear 7 Oz Xl', 129, 47, 'dispatched', 4);
insert into stocks (title, price, stock, status, category_id) values ('Sobe - Tropical Energy', 890, 28, 'ordered', 3);
insert into stocks (title, price, stock, status, category_id) values ('Rum - White, Gg White', 760, 47, 'dispatched', 7);
insert into stocks (title, price, stock, status, category_id) values ('Water Chestnut - Canned', 295, 4, 'dispatched', 5);
insert into stocks (title, price, stock, status, category_id) values ('Pasta - Angel Hair', 575, 65, 'dispatched', 9);
insert into stocks (title, price, stock, status, category_id) values ('Oranges', 611, 61, 'dispatched', 2);
insert into stocks (title, price, stock, status, category_id) values ('Pepper - Jalapeno', 687, 70, 'dispatched', 2);
insert into stocks (title, price, stock, status, category_id) values ('Pepper - Scotch Bonnet', 774, 35, 'dispatched', 7);
insert into stocks (title, price, stock, status, category_id) values ('Pie Filling - Cherry', 989, 15, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('Cake - Miini Cheesecake Cherry', 496, 62, 'ordered', 8);
insert into stocks (title, price, stock, status, category_id) values ('Cheese - Manchego, Spanish', 467, 73, 'ordered', 1);
insert into stocks (title, price, stock, status, category_id) values ('Mushroom - Oyster, Fresh', 943, 12, 'ordered', 2);
insert into stocks (title, price, stock, status, category_id) values ('Onions - Vidalia', 923, 28, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('Bread - Dark Rye, Loaf', 970, 11, 'dispatched', 8);
insert into stocks (title, price, stock, status, category_id) values ('Gloves - Goldtouch Disposable', 520, 100, 'ordered', 4);
insert into stocks (title, price, stock, status, category_id) values ('Beans - Fava, Canned', 374, 85, 'ordered', 11);
insert into stocks (title, price, stock, status, category_id) values ('Beef - Sushi Flat Iron Steak', 718, 61, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('Relish', 501, 69, 'dispatched', 11);
insert into stocks (title, price, stock, status, category_id) values ('Vodka - Smirnoff', 873, 10, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Chocolate - Milk', 972, 80, 'ordered', 2);
insert into stocks (title, price, stock, status, category_id) values ('Truffle Cups - Brown', 220, 15, 'dispatched', 6);
insert into stocks (title, price, stock, status, category_id) values ('Cookie Dough - Chocolate Chip', 875, 91, 'dispatched', 8);
insert into stocks (title, price, stock, status, category_id) values ('Carrots - Jumbo', 747, 28, 'ordered', 3);
insert into stocks (title, price, stock, status, category_id) values ('Oil - Truffle, Black', 186, 48, 'ordered', 11);
insert into stocks (title, price, stock, status, category_id) values ('Cheese - Colby', 556, 68, 'ordered', 4);
insert into stocks (title, price, stock, status, category_id) values ('Kolrabi', 421, 31, 'dispatched', 5);
insert into stocks (title, price, stock, status, category_id) values ('Pop - Club Soda Can', 743, 90, 'dispatched', 6);
insert into stocks (title, price, stock, status, category_id) values ('Milk Powder', 723, 100, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Tomato Paste', 313, 93, 'dispatched', 10);
insert into stocks (title, price, stock, status, category_id) values ('Wine - Red, Wolf Blass, Yellow', 247, 70, 'dispatched', 2);
insert into stocks (title, price, stock, status, category_id) values ('Sambuca - Opal Nera', 232, 41, 'ordered', 1);
insert into stocks (title, price, stock, status, category_id) values ('Wine - Pinot Grigio Collavini', 747, 86, 'dispatched', 10);
insert into stocks (title, price, stock, status, category_id) values ('V8 - Tropical Blend', 552, 34, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('The Pop Shoppe - Grape', 591, 77, 'ordered', 10);
insert into stocks (title, price, stock, status, category_id) values ('Eggplant Oriental', 947, 13, 'ordered', 8);
insert into stocks (title, price, stock, status, category_id) values ('Bread - French Stick', 343, 81, 'dispatched', 2);
insert into stocks (title, price, stock, status, category_id) values ('Caviar - Salmon', 361, 6, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('Wine - White, Pinot Grigio', 937, 3, 'dispatched', 5);
insert into stocks (title, price, stock, status, category_id) values ('Soup - Knorr, Chicken Noodle', 748, 46, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Coconut - Whole', 538, 64, 'ordered', 8);
insert into stocks (title, price, stock, status, category_id) values ('Veal - Liver', 385, 52, 'dispatched', 10);
insert into stocks (title, price, stock, status, category_id) values ('Bread - Petit Baguette', 103, 34, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Calypso - Black Cherry Lemonade', 752, 84, 'ordered', 4);
insert into stocks (title, price, stock, status, category_id) values ('Soup - Boston Clam Chowder', 135, 53, 'dispatched', 5);
insert into stocks (title, price, stock, status, category_id) values ('Parsnip', 944, 20, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('Chicken Thigh - Bone Out', 835, 22, 'ordered', 3);
insert into stocks (title, price, stock, status, category_id) values ('Sugar - Individual Portions', 588, 46, 'dispatched', 8);
insert into stocks (title, price, stock, status, category_id) values ('Wine - Fino Tio Pepe Gonzalez', 593, 64, 'dispatched', 7);
insert into stocks (title, price, stock, status, category_id) values ('Coffee Cup 12oz 5342cd', 361, 66, 'dispatched', 5);
insert into stocks (title, price, stock, status, category_id) values ('Pepper - Chili Powder', 671, 95, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('Dates', 433, 13, 'dispatched', 6);
insert into stocks (title, price, stock, status, category_id) values ('Cinnamon - Stick', 945, 70, 'dispatched', 4);
insert into stocks (title, price, stock, status, category_id) values ('Straw - Regular', 720, 77, 'ordered', 1);
insert into stocks (title, price, stock, status, category_id) values ('Water - Perrier', 681, 62, 'ordered', 1);
insert into stocks (title, price, stock, status, category_id) values ('Vinegar - Champagne', 910, 39, 'ordered', 4);
insert into stocks (title, price, stock, status, category_id) values ('Tea - Orange Pekoe', 257, 30, 'ordered', 11);
insert into stocks (title, price, stock, status, category_id) values ('Wine - Fontanafredda Barolo', 331, 26, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Veal - Shank, Pieces', 842, 12, 'ordered', 6);
insert into stocks (title, price, stock, status, category_id) values ('Island Oasis - Lemonade', 803, 98, 'dispatched', 8);
insert into stocks (title, price, stock, status, category_id) values ('Vinegar - Balsamic, White', 168, 97, 'dispatched', 4);
insert into stocks (title, price, stock, status, category_id) values ('Beer - Sleemans Honey Brown', 478, 20, 'ordered', 1);
insert into stocks (title, price, stock, status, category_id) values ('Ham - Proscuitto', 955, 87, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('Tomato - Peeled Italian Canned', 670, 65, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Iced Tea - Lemon, 340ml', 948, 59, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('Coffee Cup 12oz 5342cd', 654, 88, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Bacardi Breezer - Tropical', 671, 40, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Radish', 304, 32, 'ordered', 3);
insert into stocks (title, price, stock, status, category_id) values ('Smoked Tongue', 354, 70, 'ordered', 8);
insert into stocks (title, price, stock, status, category_id) values ('Juice - Grape, White', 877, 59, 'ordered', 7);
insert into stocks (title, price, stock, status, category_id) values ('Calypso - Black Cherry Lemonade', 201, 39, 'dispatched', 6);
insert into stocks (title, price, stock, status, category_id) values ('Soup - Beef, Base Mix', 728, 89, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Pork - Loin, Center Cut', 631, 25, 'ordered', 2);
insert into stocks (title, price, stock, status, category_id) values ('Beer - Labatt Blue', 939, 41, 'dispatched', 5);
insert into stocks (title, price, stock, status, category_id) values ('Pepper - Chipotle, Canned', 837, 61, 'ordered', 8);
insert into stocks (title, price, stock, status, category_id) values ('Shichimi Togarashi Peppeers', 266, 32, 'dispatched', 9);
insert into stocks (title, price, stock, status, category_id) values ('Bread - Crumbs, Bulk', 227, 15, 'ordered', 3);
insert into stocks (title, price, stock, status, category_id) values ('Cabbage - Savoy', 747, 54, 'ordered', 1);
insert into stocks (title, price, stock, status, category_id) values ('Ecolab - Balanced Fusion', 436, 76, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('Wine - Red, Cabernet Merlot', 699, 47, 'ordered', 1);
insert into stocks (title, price, stock, status, category_id) values ('Longos - Grilled Veg Sandwiches', 269, 12, 'ordered', 6);
insert into stocks (title, price, stock, status, category_id) values ('Pail For Lid 1537', 634, 81, 'dispatched', 10);
insert into stocks (title, price, stock, status, category_id) values ('Asparagus - Frozen', 525, 43, 'dispatched', 11);
insert into stocks (title, price, stock, status, category_id) values ('Rum - Mount Gay Eclipes', 120, 4, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('Gatorade - Lemon Lime', 270, 7, 'ordered', 9);
insert into stocks (title, price, stock, status, category_id) values ('Bar Nature Valley', 853, 4, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Muffin Batt - Choc Chk', 219, 81, 'ordered', 10);
insert into stocks (title, price, stock, status, category_id) values ('Grapefruit - White', 369, 77, 'dispatched', 8);
insert into stocks (title, price, stock, status, category_id) values ('Kiwi', 222, 61, 'ordered', 7);
insert into stocks (title, price, stock, status, category_id) values ('Cheese - Colby', 963, 36, 'ordered', 2);
insert into stocks (title, price, stock, status, category_id) values ('True - Vue Containers', 466, 39, 'dispatched', 2);
insert into stocks (title, price, stock, status, category_id) values ('Mcguinness - Blue Curacao', 150, 4, 'ordered', 10);
insert into stocks (title, price, stock, status, category_id) values ('Chevril', 422, 58, 'dispatched', 7);
insert into stocks (title, price, stock, status, category_id) values ('Oil - Food, Lacquer Spray', 103, 47, 'dispatched', 4);
insert into stocks (title, price, stock, status, category_id) values ('Oil - Truffle, Black', 253, 29, 'dispatched', 2);
insert into stocks (title, price, stock, status, category_id) values ('Cheese - Pont Couvert', 504, 57, 'ordered', 7);
insert into stocks (title, price, stock, status, category_id) values ('Cake - Mini Cheesecake', 925, 99, 'dispatched', 6);
insert into stocks (title, price, stock, status, category_id) values ('Soup - Campbells Asian Noodle', 105, 86, 'ordered', 2);
insert into stocks (title, price, stock, status, category_id) values ('Cleaner - Comet', 722, 48, 'dispatched', 6);
insert into stocks (title, price, stock, status, category_id) values ('Beans - Soya Bean', 166, 74, 'dispatched', 5);
insert into stocks (title, price, stock, status, category_id) values ('Pork - Bacon Cooked Slcd', 514, 53, 'ordered', 9);
insert into stocks (title, price, stock, status, category_id) values ('Scallops - U - 10', 637, 2, 'dispatched', 8);
insert into stocks (title, price, stock, status, category_id) values ('Cheese - Camembert', 491, 96, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Broom - Corn', 601, 38, 'ordered', 4);
insert into stocks (title, price, stock, status, category_id) values ('Longos - Grilled Chicken With', 296, 72, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('Tilapia - Fillets', 225, 6, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Parasol Pick Stir Stick', 320, 8, 'dispatched', 4);
insert into stocks (title, price, stock, status, category_id) values ('Lamb Rack - Ontario', 447, 87, 'dispatched', 4);
insert into stocks (title, price, stock, status, category_id) values ('Pasta - Penne, Rigate, Dry', 449, 62, 'ordered', 2);
insert into stocks (title, price, stock, status, category_id) values ('Cheese - Goat', 340, 36, 'dispatched', 9);
insert into stocks (title, price, stock, status, category_id) values ('Beef Flat Iron Steak', 104, 94, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Maintenance Removal Charge', 713, 18, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Chick Peas - Canned', 669, 25, 'dispatched', 7);
insert into stocks (title, price, stock, status, category_id) values ('Currants', 265, 90, 'ordered', 9);
insert into stocks (title, price, stock, status, category_id) values ('Energy - Boo - Koo', 783, 97, 'dispatched', 8);
insert into stocks (title, price, stock, status, category_id) values ('Bacardi Limon', 360, 81, 'dispatched', 11);
insert into stocks (title, price, stock, status, category_id) values ('Foil - Round Foil', 819, 22, 'dispatched', 5);
insert into stocks (title, price, stock, status, category_id) values ('Tia Maria', 128, 51, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Duck - Fat', 171, 94, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Steamers White', 882, 61, 'dispatched', 8);
insert into stocks (title, price, stock, status, category_id) values ('Sorrel - Fresh', 501, 53, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Red Currants', 237, 38, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('Egg - Salad Premix', 688, 20, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Squash - Guords', 963, 18, 'ordered', 8);
insert into stocks (title, price, stock, status, category_id) values ('Appetizer - Asian Shrimp Roll', 644, 94, 'dispatched', 2);
insert into stocks (title, price, stock, status, category_id) values ('Blueberries', 678, 76, 'ordered', 9);
insert into stocks (title, price, stock, status, category_id) values ('The Pop Shoppe - Black Cherry', 989, 49, 'ordered', 1);
insert into stocks (title, price, stock, status, category_id) values ('Beer - Original Organic Lager', 509, 52, 'dispatched', 5);
insert into stocks (title, price, stock, status, category_id) values ('Pastrami', 557, 83, 'ordered', 6);
insert into stocks (title, price, stock, status, category_id) values ('Goat - Leg', 204, 65, 'ordered', 4);
insert into stocks (title, price, stock, status, category_id) values ('Pepper - Roasted Red', 148, 65, 'ordered', 1);
insert into stocks (title, price, stock, status, category_id) values ('Beef Striploin Aaa', 704, 81, 'ordered', 8);
insert into stocks (title, price, stock, status, category_id) values ('Lettuce - Frisee', 281, 18, 'ordered', 4);
insert into stocks (title, price, stock, status, category_id) values ('Mcguinness - Blue Curacao', 175, 6, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Puree - Guava', 810, 79, 'dispatched', 10);
insert into stocks (title, price, stock, status, category_id) values ('Chips - Potato Jalapeno', 594, 96, 'dispatched', 10);
insert into stocks (title, price, stock, status, category_id) values ('Sparkling Wine - Rose, Freixenet', 641, 63, 'ordered', 2);
insert into stocks (title, price, stock, status, category_id) values ('Banana Turning', 161, 94, 'dispatched', 9);
insert into stocks (title, price, stock, status, category_id) values ('Icecream - Dstk Strw Chseck', 140, 48, 'dispatched', 10);
insert into stocks (title, price, stock, status, category_id) values ('Port - 74 Brights', 333, 2, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Iced Tea Concentrate', 666, 65, 'ordered', 4);
insert into stocks (title, price, stock, status, category_id) values ('Chocolate - Unsweetened', 899, 71, 'dispatched', 5);
insert into stocks (title, price, stock, status, category_id) values ('Coffee - Hazelnut Cream', 774, 40, 'dispatched', 8);
insert into stocks (title, price, stock, status, category_id) values ('Garam Marsala', 489, 68, 'ordered', 9);
insert into stocks (title, price, stock, status, category_id) values ('Salt - Celery', 241, 64, 'dispatched', 4);
insert into stocks (title, price, stock, status, category_id) values ('Yeast Dry - Fleischman', 513, 22, 'dispatched', 11);
insert into stocks (title, price, stock, status, category_id) values ('Piping - Bags Quizna', 285, 2, 'ordered', 6);
insert into stocks (title, price, stock, status, category_id) values ('Rye Special Old', 543, 71, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Lentils - Green Le Puy', 308, 87, 'dispatched', 8);
insert into stocks (title, price, stock, status, category_id) values ('Thyme - Dried', 295, 53, 'dispatched', 4);
insert into stocks (title, price, stock, status, category_id) values ('Pastry - Banana Muffin - Mini', 702, 80, 'ordered', 2);
insert into stocks (title, price, stock, status, category_id) values ('Apple - Delicious, Golden', 520, 8, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Bread - Flat Bread', 471, 30, 'ordered', 10);
insert into stocks (title, price, stock, status, category_id) values ('Nutmeg - Ground', 472, 11, 'ordered', 1);
insert into stocks (title, price, stock, status, category_id) values ('Mahi Mahi', 506, 86, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Tuna - Canned, Flaked, Light', 170, 76, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Sping Loaded Cup Dispenser', 228, 88, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Olives - Nicoise', 152, 96, 'dispatched', 10);
insert into stocks (title, price, stock, status, category_id) values ('Venison - Ground', 612, 64, 'dispatched', 4);
insert into stocks (title, price, stock, status, category_id) values ('Shrimp - Black Tiger 16/20', 177, 75, 'ordered', 9);
insert into stocks (title, price, stock, status, category_id) values ('Pasta - Rotini, Colour, Dry', 289, 48, 'dispatched', 4);
insert into stocks (title, price, stock, status, category_id) values ('Wine - Wyndham Estate Bin 777', 977, 27, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('Pork - Backfat', 692, 97, 'ordered', 9);
insert into stocks (title, price, stock, status, category_id) values ('Veal - Inside', 462, 16, 'dispatched', 2);
insert into stocks (title, price, stock, status, category_id) values ('Lettuce - Frisee', 307, 63, 'dispatched', 5);
insert into stocks (title, price, stock, status, category_id) values ('Flour - Strong Pizza', 727, 1, 'dispatched', 11);
insert into stocks (title, price, stock, status, category_id) values ('Beer - Blue', 789, 26, 'dispatched', 9);
insert into stocks (title, price, stock, status, category_id) values ('Nantucket - Orange Mango Cktl', 937, 40, 'dispatched', 11);
insert into stocks (title, price, stock, status, category_id) values ('Flour - Cake', 628, 42, 'ordered', 2);
insert into stocks (title, price, stock, status, category_id) values ('Parsnip', 198, 59, 'ordered', 9);
insert into stocks (title, price, stock, status, category_id) values ('Flower - Commercial Spider', 735, 53, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('Ice Cream Bar - Hagen Daz', 453, 11, 'dispatched', 5);
insert into stocks (title, price, stock, status, category_id) values ('Tart Shells - Savory, 3', 285, 33, 'dispatched', 9);
insert into stocks (title, price, stock, status, category_id) values ('Breakfast Quesadillas', 577, 74, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Banana Turning', 889, 81, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('Juice - Apple 284ml', 324, 75, 'dispatched', 6);
insert into stocks (title, price, stock, status, category_id) values ('Chicken - Leg, Boneless', 513, 71, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Godiva White Chocolate', 101, 55, 'ordered', 3);
insert into stocks (title, price, stock, status, category_id) values ('Bread - Olive', 102, 64, 'ordered', 4);
insert into stocks (title, price, stock, status, category_id) values ('Mangoes', 720, 48, 'dispatched', 9);
insert into stocks (title, price, stock, status, category_id) values ('Fish - Artic Char, Cold Smoked', 890, 30, 'ordered', 9);
insert into stocks (title, price, stock, status, category_id) values ('Lidsoupcont Rp12dn', 148, 72, 'dispatched', 11);
insert into stocks (title, price, stock, status, category_id) values ('Chicken - Bones', 194, 27, 'dispatched', 10);
insert into stocks (title, price, stock, status, category_id) values ('Container - Foam Dixie 12 Oz', 358, 10, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Spice - Onion Powder Granulated', 336, 15, 'dispatched', 4);
insert into stocks (title, price, stock, status, category_id) values ('Ginger - Crystalized', 930, 79, 'dispatched', 7);
insert into stocks (title, price, stock, status, category_id) values ('Cauliflower', 846, 49, 'dispatched', 8);
insert into stocks (title, price, stock, status, category_id) values ('Bar - Sweet And Salty Chocolate', 655, 35, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Shrimp - Prawn', 758, 78, 'ordered', 6);
insert into stocks (title, price, stock, status, category_id) values ('Iced Tea - Lemon, 460 Ml', 386, 71, 'dispatched', 11);
insert into stocks (title, price, stock, status, category_id) values ('Tabasco Sauce, 2 Oz', 844, 40, 'ordered', 3);
insert into stocks (title, price, stock, status, category_id) values ('Soup - Campbells Tomato Ravioli', 292, 37, 'dispatched', 6);
insert into stocks (title, price, stock, status, category_id) values ('Sauce - Soya, Dark', 841, 85, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('Wine - Baron De Rothschild', 446, 60, 'dispatched', 9);
insert into stocks (title, price, stock, status, category_id) values ('Sauce - Bernaise, Mix', 627, 31, 'dispatched', 6);
insert into stocks (title, price, stock, status, category_id) values ('Pork - Ham, Virginia', 515, 21, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Rabbit - Frozen', 219, 36, 'dispatched', 4);
insert into stocks (title, price, stock, status, category_id) values ('Beef - Cow Feet Split', 321, 100, 'dispatched', 10);
insert into stocks (title, price, stock, status, category_id) values ('Cheese - Shred Cheddar / Mozza', 281, 69, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('Fiddlehead - Frozen', 423, 25, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Pasta - Agnolotti - Butternut', 212, 25, 'dispatched', 2);
insert into stocks (title, price, stock, status, category_id) values ('Beef - Tender Tips', 742, 67, 'dispatched', 10);
insert into stocks (title, price, stock, status, category_id) values ('Pork - Tenderloin, Fresh', 597, 54, 'ordered', 3);
insert into stocks (title, price, stock, status, category_id) values ('Soup Campbells - Italian Wedding', 499, 17, 'dispatched', 9);
insert into stocks (title, price, stock, status, category_id) values ('Cocoa Feuilletine', 722, 62, 'ordered', 4);
insert into stocks (title, price, stock, status, category_id) values ('Beans - Kidney, Canned', 415, 42, 'ordered', 1);
insert into stocks (title, price, stock, status, category_id) values ('Nantucket - Kiwi Berry Cktl.', 166, 36, 'ordered', 10);
insert into stocks (title, price, stock, status, category_id) values ('Wine - Marlbourough Sauv Blanc', 855, 9, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Oil - Coconut', 608, 78, 'dispatched', 6);
insert into stocks (title, price, stock, status, category_id) values ('Ham - Cooked', 934, 97, 'dispatched', 9);
insert into stocks (title, price, stock, status, category_id) values ('Coffee Cup 12oz 5342cd', 893, 64, 'dispatched', 11);
insert into stocks (title, price, stock, status, category_id) values ('Nut - Almond, Blanched, Sliced', 171, 78, 'dispatched', 7);
insert into stocks (title, price, stock, status, category_id) values ('Ice Cream Bar - Hagen Daz', 937, 13, 'ordered', 11);
insert into stocks (title, price, stock, status, category_id) values ('Tabasco Sauce, 2 Oz', 478, 20, 'dispatched', 2);
insert into stocks (title, price, stock, status, category_id) values ('Glove - Cutting', 314, 6, 'dispatched', 2);
insert into stocks (title, price, stock, status, category_id) values ('Wine - Placido Pinot Grigo', 515, 59, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Soup Campbells Split Pea And Ham', 372, 9, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Huck White Towels', 969, 27, 'dispatched', 6);
insert into stocks (title, price, stock, status, category_id) values ('Wine - George Duboeuf Rose', 619, 5, 'dispatched', 4);
insert into stocks (title, price, stock, status, category_id) values ('Rabbit - Frozen', 620, 31, 'ordered', 6);
insert into stocks (title, price, stock, status, category_id) values ('Lobster - Tail, 3 - 4 Oz', 446, 54, 'dispatched', 6);
insert into stocks (title, price, stock, status, category_id) values ('Mayonnaise', 239, 11, 'ordered', 1);
insert into stocks (title, price, stock, status, category_id) values ('Pastry - Carrot Muffin - Mini', 743, 3, 'ordered', 6);
insert into stocks (title, price, stock, status, category_id) values ('Grand Marnier', 795, 53, 'dispatched', 1);
insert into stocks (title, price, stock, status, category_id) values ('Bread - Frozen Basket Variety', 369, 52, 'ordered', 1);
insert into stocks (title, price, stock, status, category_id) values ('Chocolate Bar - Oh Henry', 861, 22, 'dispatched', 11);
insert into stocks (title, price, stock, status, category_id) values ('Bar Mix - Pina Colada, 355 Ml', 348, 81, 'ordered', 8);
insert into stocks (title, price, stock, status, category_id) values ('Capers - Pickled', 606, 64, 'dispatched', 4);
insert into stocks (title, price, stock, status, category_id) values ('Lettuce - Green Leaf', 195, 73, 'dispatched', 2);
insert into stocks (title, price, stock, status, category_id) values ('Salmon - Atlantic, Fresh, Whole', 183, 52, 'ordered', 4);
insert into stocks (title, price, stock, status, category_id) values ('Swordfish Loin Portions', 547, 82, 'dispatched', 11);
insert into stocks (title, price, stock, status, category_id) values ('Wine - Sherry Dry Sack, William', 724, 26, 'ordered', 9);
insert into stocks (title, price, stock, status, category_id) values ('Wine - Charddonnay Errazuriz', 288, 6, 'dispatched', 5);
insert into stocks (title, price, stock, status, category_id) values ('Rice - Wild', 672, 54, 'ordered', 11);
insert into stocks (title, price, stock, status, category_id) values ('Beef - Kobe Striploin', 722, 82, 'ordered', 7);
insert into stocks (title, price, stock, status, category_id) values ('Soup - Campbells Chicken', 374, 70, 'dispatched', 5);
insert into stocks (title, price, stock, status, category_id) values ('Bread - Roll, Soft White Round', 400, 56, 'ordered', 2);
insert into stocks (title, price, stock, status, category_id) values ('Foam Tray S2', 700, 50, 'ordered', 10);
insert into stocks (title, price, stock, status, category_id) values ('Cheese - Sheep Milk', 275, 74, 'ordered', 1);
insert into stocks (title, price, stock, status, category_id) values ('Creamers - 10%', 114, 1, 'ordered', 8);
insert into stocks (title, price, stock, status, category_id) values ('Bread - Frozen Basket Variety', 773, 6, 'dispatched', 2);
insert into stocks (title, price, stock, status, category_id) values ('Eggwhite Frozen', 995, 56, 'dispatched', 4);
insert into stocks (title, price, stock, status, category_id) values ('Truffle Cups - Red', 639, 100, 'dispatched', 11);
insert into stocks (title, price, stock, status, category_id) values ('Potatoes - Idaho 100 Count', 262, 69, 'dispatched', 7);
insert into stocks (title, price, stock, status, category_id) values ('Soup - Cream Of Broccoli, Dry', 247, 79, 'ordered', 10);
insert into stocks (title, price, stock, status, category_id) values ('Snapple - Mango Maddness', 868, 3, 'ordered', 3);
insert into stocks (title, price, stock, status, category_id) values ('Food Colouring - Green', 799, 100, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Bagel - Plain', 118, 65, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Potatoes - Parissienne', 199, 42, 'ordered', 4);
insert into stocks (title, price, stock, status, category_id) values ('Numi - Assorted Teas', 584, 37, 'dispatched', 11);
insert into stocks (title, price, stock, status, category_id) values ('Soup - Campbells', 887, 46, 'ordered', 4);
insert into stocks (title, price, stock, status, category_id) values ('Smirnoff Green Apple Twist', 756, 64, 'dispatched', 9);
insert into stocks (title, price, stock, status, category_id) values ('Lettuce - Romaine, Heart', 874, 8, 'dispatched', 7);
insert into stocks (title, price, stock, status, category_id) values ('Wine - Balbach Riverside', 809, 51, 'ordered', 2);
insert into stocks (title, price, stock, status, category_id) values ('Wine - Crozes Hermitage E.', 112, 72, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Bay Leaf Ground', 935, 49, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Mushrooms - Honey', 704, 62, 'ordered', 11);
insert into stocks (title, price, stock, status, category_id) values ('Pickles - Gherkins', 439, 79, 'ordered', 7);
insert into stocks (title, price, stock, status, category_id) values ('Sobe - Berry Energy', 956, 56, 'ordered', 8);
insert into stocks (title, price, stock, status, category_id) values ('Oil - Shortening,liqud, Fry', 345, 36, 'ordered', 1);
insert into stocks (title, price, stock, status, category_id) values ('Eggs - Extra Large', 540, 10, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Milk - Skim', 189, 2, 'dispatched', 2);
insert into stocks (title, price, stock, status, category_id) values ('Bar - Sweet And Salty Chocolate', 721, 33, 'ordered', 7);
insert into stocks (title, price, stock, status, category_id) values ('Bay Leaf Ground', 710, 15, 'dispatched', 4);
insert into stocks (title, price, stock, status, category_id) values ('Crab - Back Fin Meat, Canned', 602, 58, 'ordered', 1);
insert into stocks (title, price, stock, status, category_id) values ('Soup - Knorr, Classic Can. Chili', 879, 88, 'dispatched', 7);
insert into stocks (title, price, stock, status, category_id) values ('Beef - Tenderlion, Center Cut', 425, 1, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Squid U5 - Thailand', 582, 1, 'dispatched', 8);
insert into stocks (title, price, stock, status, category_id) values ('Tomato - Tricolor Cherry', 225, 89, 'dispatched', 4);
insert into stocks (title, price, stock, status, category_id) values ('Ice Cream Bar - Oreo Cone', 228, 96, 'ordered', 8);
insert into stocks (title, price, stock, status, category_id) values ('Mangostein', 339, 49, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Tuna - Canned, Flaked, Light', 800, 36, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Appetizer - Mushroom Tart', 403, 90, 'dispatched', 2);
insert into stocks (title, price, stock, status, category_id) values ('Boogies', 903, 91, 'ordered', 6);
insert into stocks (title, price, stock, status, category_id) values ('Compound - Pear', 456, 78, 'dispatched', 3);
insert into stocks (title, price, stock, status, category_id) values ('Coffee - Ristretto Coffee Capsule', 735, 14, 'ordered', 11);
insert into stocks (title, price, stock, status, category_id) values ('Wine - Chateauneuf Du Pape', 954, 57, 'ordered', 8);
insert into stocks (title, price, stock, status, category_id) values ('Bread - Kimel Stick Poly', 960, 19, 'ordered', 5);
insert into stocks (title, price, stock, status, category_id) values ('Coffee - French Vanilla Frothy', 125, 68, 'dispatched', 7);
insert into stocks (title, price, stock, status, category_id) values ('Squid Ink', 927, 9, 'ordered', 8);
